import os
import json
from collections import Counter, defaultdict

# Map file extensions to language names
EXT_TO_LANG = {
    ".py": "Python",
    ".java": "Java",
    ".cpp": "C++",
    ".cc": "C++",
    ".cxx": "C++",
    ".c": "C",
    ".js": "JavaScript",
    ".ts": "TypeScript",
    ".go": "Go",
    ".rb": "Ruby",
    ".rs": "Rust",
    ".cs": "C#",
    ".kt": "Kotlin",
    ".swift": "Swift",
    ".php": "PHP",
    ".sql": "SQL",
    ".scala": "Scala",
    ".sh": "Shell",
}

DIFFICULTIES = ["Easy", "Medium", "Hard"]

def find_solution_files(base_dir: str):
    """
    Find code files under base_dir, excluding markdown/problem statements and hidden folders.
    """
    code_files = []
    for root, dirs, files in os.walk(base_dir):
        # Skip hidden/system dirs
        dirs[:] = [d for d in dirs if not d.startswith(".") and d not in ("__pycache__", "node_modules", ".git")]

        for f in files:
            if f.startswith("."):
                continue
            # ignore common non-solution artifacts
            if f.lower().endswith((".md", ".txt", ".json")):
                continue
            path = os.path.join(root, f)
            code_files.append(path)
    return code_files

def language_from_filename(path: str) -> str:
    _, ext = os.path.splitext(path.lower())
    return EXT_TO_LANG.get(ext, f"Other ({ext or 'no-ext'})")

def pct(n: int, total: int) -> str:
    if total == 0:
        return "0.0%"
    return f"{(n * 100.0 / total):.1f}%"

def main():
    repo_root = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
    leetcode_root = os.path.join(repo_root, "leetcode")

    results = {}
    overall_counter = Counter()

    for diff in DIFFICULTIES:
        diff_dir = os.path.join(leetcode_root, diff)
        if not os.path.isdir(diff_dir):
            results[diff] = {"total_files": 0, "languages": {}}
            continue

        files = find_solution_files(diff_dir)
        counter = Counter(language_from_filename(p) for p in files)

        total = sum(counter.values())
        overall_counter.update(counter)

        results[diff] = {
            "total_files": total,
            "languages": {lang: {"count": c, "percent": pct(c, total)} for lang, c in counter.most_common()}
        }

    overall_total = sum(overall_counter.values())
    results["Overall"] = {
        "total_files": overall_total,
        "languages": {lang: {"count": c, "percent": pct(c, overall_total)} for lang, c in overall_counter.most_common()}
    }

    # Write JSON
    os.makedirs(leetcode_root, exist_ok=True)
    json_path = os.path.join(leetcode_root, "analysis.json")
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(results, f, indent=2)

    # Write Markdown report
    md_path = os.path.join(leetcode_root, "ANALYSIS.md")
    lines = []
    lines.append("# LeetCode Language Analysis\n")
    lines.append("This report is auto-generated by the GitHub Action workflow.\n")

    for section in DIFFICULTIES + ["Overall"]:
        section_data = results.get(section, {})
        total_files = section_data.get("total_files", 0)

        lines.append(f"## {section}\n")
        lines.append(f"Total solution files detected: **{total_files}**\n")

        langs = section_data.get("languages", {})
        if not langs:
            lines.append("_No solution files found._\n")
            continue

        lines.append("| Language | Count | Percent |\n")
        lines.append("|---|---:|---:|\n")
        for lang, meta in langs.items():
            lines.append(f"| {lang} | {meta['count']} | {meta['percent']} |\n")
        lines.append("\n")

    with open(md_path, "w", encoding="utf-8") as f:
        f.writelines(lines)

    print(f"Wrote {json_path}")
    print(f"Wrote {md_path}")

if __name__ == "__main__":
    main()
